
import DocFormat
import SectionFormat

def Generate_text_coverpage(pdf):
    pdf.set_font(DocFormat.SetFont_Family, style="B", size=24)
    pdf.ln(80)
    pdf.multi_cell(0, 10, "This is the cover page\nGenerated by SarabunLM", align="C", ln=True)
    pdf.ln(5)

def Generate_text_content(pdf):
      pdf.add_page()
      pdf.set_font(DocFormat.SetFont_Family, style=DocFormat.SetFont_Style, size=DocFormat.SetFont_Size)
      pdf.multi_cell(50, 10, "content\n", ln=True)
      pdf.multi_cell(50, 10,"This is the table of contents\nGenerated by SarabunLM", ln=True)
      pdf.ln(5)
   